# -*- coding: utf-8 -*-
"""Traduction française des éléments uniques inclusions/exclusions."""
import sys
sys.path.insert(0, '.')
from _bullets_ko import bangun

INC = [
 "Transport climatisé adapté à la taille du groupe",
 "Bateau privé pour l'<strong>île de Bunaken&nbsp;</strong>",
 "3 nuits d'hébergement à l'hôtel sélectionné – chambre twin/double",
 "Guide expérimenté &amp; chauffeur",
 "Frais d'entrée aux sites touristiques &amp; frais de parking",
 "Repas selon le programme",
 "Services de tour selon l'itinéraire",
 "Eau minérale 1 bouteille/pers/jour",
 "Service d'accueil",
 "Bateau privé pour <strong>l'île de Bunaken &amp; l'île de Lihaga</strong>",
 "4 nuits d'hébergement à l'hôtel sélectionné – chambre twin/double",
 "Bateau privé pour l'île de Lihaga",
 "2 nuits d'hébergement à l'hôtel sélectionné – chambre twin/double",
 "Bateau privé pour <strong>l'île de Bunaken</strong>",
 "Instructeur professionnel de parapente",
 "Frais d'entrée aux sites",
 "Services de tour selon le programme",
 "Transport climatisé selon le nombre de participants",
 "Guide de mangrove expérimenté et chauffeur",
 "Canoë",
 "Frais d'entrée aux sites touristiques&nbsp;",
 "Frais de parking",
 "1 bouteille d'eau minérale par personne",
 "Transport climatisé selon le nombre de participants",
 "Ranger à la réserve naturelle de Tangkoko",
 "Guide et chauffeur expérimentés",
 "Frais d'entrée aux sites touristiques",
 "Déjeuner",
 "Une bouteille d'eau minérale par personne",
 "Guide et chauffeur expérimentés, frais d'entrée aux sites touristiques",
 "Services selon le programme",
 "Équipement de rafting",
 "Bateau privé pour l'île de Bunaken",
 "Guide de tour expérimenté &amp; batelier",
 "Frais d'entrée aux sites touristiques",
 "Déjeuner dans un restaurant local",
 "Une bouteille d'eau minérale par personne",
 "Services de tour selon l'itinéraire",
 "Transport climatisé selon le nombre de participants",
 "Guide expérimenté (parlant anglais) &amp; chauffeur",
 "Frais d'entrée &amp; frais de parking",
 "Services de tour selon le programme",
 "Transport climatisé&nbsp;",
 "Bateau privé pour l'île de Bunaken",
 "Séjour de 5 nuits à l'hôtel, occupation double",
 "Billets d'entrée aux sites touristiques &amp; frais de parking",
 "Repas selon le programme du tour",
 "Une bouteille d'eau minérale par personne et par jour",
 "Transport climatisé selon le nombre de participants",
 "2 nuits à Tangkoko &amp; 1 nuit à Tomohon (lit double/twin)",
 "Chauffeur &amp; guide expérimentés",
 "Ranger du parc naturel de Tangkoko",
 "Billets d'entrée aux sites &amp; frais de parking",
 "Repas selon l'itinéraire du tour",
 "Services de tour selon le programme",
 "2 bouteilles d'eau minérale par jour",
 "2 nuits à Tangkoko (lit double/twin)",
 "Repas selon le programme",
 "Bateau privé pour 3 îles",
 "Guide de tour expérimenté &amp; batelier",
 "Services de tour selon l'itinéraire",
 "Transport climatisé selon le nombre de participants",
 "Guide et chauffeur expérimentés",
 "Frais de parking &amp; de don&nbsp;",
 "Une bouteille d'eau minérale par personne&nbsp;",
 "Services de tour selon le programme",
 "Transfert aéroport",
 "Green fee le jour 2",
 "Voiturette de golf et frais de caddie (pourboire caddie exclu) le jour 2",
 "Bateau privé pour l'île de Lihaga",
 "Guide de tour professionnel le jour 3",
 "Bateau privé pour l'île de Bunaken",
 "Green fee les jours 2 &amp; 3",
 "Voiturette de golf et frais de caddie (pourboire caddie exclu)&nbsp;",
 "Transfert aéroport&nbsp;",
 "Chambre (occupation double – lits double/twin)",
 "Repas en pension complète",
 "Forfait pension complète (basé sur 2 plongées matinales par jour sur 3 jours de plongée)",
 '<p style="text-align:justify;">Forfait pension complète (basé sur 2 plongées matinales par jour sur 3 jours de plongée)</p><p><i><strong>Tour Tangkoko</strong></i>:&nbsp;</p>',
 "Transport vers Tangkoko &amp; la cascade de Tunan",
 "1x déjeuner dans un restaurant local",
 "Guide expérimenté &amp; chauffeur",
 "Tous les frais d'entrée&nbsp;",
 "Une bouteille d'eau minérale par personne.",
 "Forfait pension complète (basé sur 2 plongées matinales par jour sur 2 jours de plongée)",
 "Transport terrestre",
 "Bateau privé pour l'île de Lihaga",
 "Guide de tour expérimenté",
 "Chauffeur &amp; batelier",
 "Frais d'entrée aux sites touristiques &amp; frais de parking",
 "Déjeuner &amp; 1 bouteille d'eau minérale par personne",
 "Bateau privé pour les îles de Gangga &amp; Lihaga",
 "Équipement de snorkeling",
 "Guide de tour, chauffeur &amp; batelier expérimentés",
 "Transport terrestre privé (voiture)&nbsp;",
 "Bateau pour l'île de Manado Tua - l'île de Bunaken",
 "Guide de tour expérimenté&nbsp;",
 "Chauffeur &amp; batelier&nbsp;",
 "Frais de parking, panier-repas&nbsp;",
 "1 bouteille d'eau minérale par personne&nbsp;",
 "Transport&nbsp;",
 "Bateau &amp; équipement de snorkeling",
]

EXC = [
 "Billet d'avion aller-retour", "Pourboires pour le guide &amp; le chauffeur", "Excursions optionnelles",
 "Dépenses personnelles hors forfait (repas/boissons supplémentaires, etc.)",
 "Service de portage, taxe d'aéroport &amp; frais de surpoids",
 "Dépenses personnelles (blanchisserie, minibar, service en chambre, etc.)",
 "Assurance voyage", "Autres frais non mentionnés dans le programme du tour", "Billet d'avion",
 "Voiture (dépose &amp; prise en charge) en option", "Taxe d'aéroport", "Portage&nbsp;", "Hôtel", "Guide",
 "Pourboire du chauffeur", "Autres frais hors programme du tour", "Portage", "Repas", "Pourboires guide &amp; chauffeur",
 "Hôtel,&nbsp;", "Pourboires pour le guide et le chauffeur", "Tout autre frais hors programme du tour",
 "Tout autre frais hors programme du tour.", "Pourboires pour le guide et le chauffeur", "Transport terrestre (voiture)",
 "Billet d'avion aller-retour", "Frais supplémentaires hors forfait (repas/boissons supplémentaires, etc.)",
 "Portage, taxe d'aéroport &amp; excédent de bagages", "Dépenses personnelles (blanchisserie, minibar, service en chambre, etc.)",
 "Assurance voyage", "Autres frais hors programme du tour", "Billet d'avion aller-retour", "Pourboires chauffeur &amp; guide",
 "Excursions optionnelles", "Frais hors forfait (repas/boissons supplémentaires, etc.)", "Portage, taxe d'aéroport &amp; excédent de bagages",
 "Et autres frais hors programme du tour", "&nbsp;Excursion optionnelle", "Transport terrestre (voiture)&nbsp;",
 "Billets d'avion aller-retour", "Location d'équipement", "Recharges nitrox",
 "Plongées de nuit &amp; du poisson-grenouille mandarin", "Excursions &amp; activités optionnelles", "Dépenses personnelles",
 "Taxe d'aéroport &amp; excédent de bagages", "Tout service non mentionné ci-dessus",
 "Location d'équipement de plongée", "Billet d'avion&nbsp;", "Service de portage", "Hébergement à l'hôtel&nbsp;",
 "Pourboires guide &amp; chauffeur", "Excursions optionnelles &amp; autres dépenses personnelles non mentionnées dans le programme",
]

bangun('fr', INC, EXC)
