# -*- coding: utf-8 -*-
"""Nederlandse vertaling van de unieke inclusions-/exclusions-items."""
import sys
sys.path.insert(0, '.')
from _bullets_ko import bangun

INC = [
 "Airconditioned vervoer afgestemd op de groepsgrootte",
 "Privéboot naar <strong>Bunaken-eiland&nbsp;</strong>",
 "3 nachten verblijf in het geselecteerde hotel – twin-/dubbele kamer",
 "Ervaren gids &amp; chauffeur",
 "Toegangskaarten voor toeristische attracties &amp; parkeergeld",
 "Maaltijden volgens het programma",
 "Reisdiensten volgens de reisroute",
 "Mineraalwater 1 fles/persoon/dag",
 "Ontvangstservice",
 "Privéboot naar <strong>Bunaken-eiland &amp; Lihaga-eiland</strong>",
 "4 nachten verblijf in het geselecteerde hotel – twin-/dubbele kamer",
 "Privéboot naar Lihaga-eiland",
 "2 nachten verblijf in het geselecteerde hotel – twin-/dubbele kamer",
 "Privéboot naar <strong>Bunaken-eiland</strong>",
 "Professionele paraglidinginstructeur",
 "Toegangskaarten voor attracties",
 "Reisdiensten volgens het programma",
 "Volledig airconditioned vervoer afgestemd op het aantal deelnemers",
 "Ervaren mangrovegids en chauffeur",
 "Kano",
 "Toegangskaarten voor toeristische attracties&nbsp;",
 "Parkeergeld",
 "1 fles mineraalwater per persoon",
 "Volledig airconditioned vervoer afgestemd op het aantal deelnemers",
 "Ranger bij het natuurreservaat Tangkoko",
 "Ervaren gids en chauffeur",
 "Toegangskaarten voor toeristische attracties",
 "Lunch",
 "Een fles mineraalwater per persoon",
 "Ervaren gids en chauffeur, toegangskaarten voor toeristische attracties",
 "Diensten volgens het programma",
 "Raftingmateriaal",
 "Privéboot naar Bunaken-eiland",
 "Ervaren reisgids &amp; bootsman",
 "Toegangskaarten voor toeristische attracties",
 "Lunch in een lokaal restaurant",
 "Een fles mineraalwater per persoon",
 "Reisdiensten volgens de reisroute",
 "Airconditioned vervoer afgestemd op het aantal deelnemers",
 "Ervaren gids (Engelssprekend) &amp; chauffeur",
 "Toegangs- &amp; parkeergeld",
 "Reisdiensten volgens het programma",
 "Airconditioned vervoer&nbsp;",
 "Privéboot naar Bunaken-eiland",
 "5 nachten hotelverblijf, tweepersoonsbezetting",
 "Toegangskaarten voor toeristische attracties &amp; parkeergeld",
 "Maaltijden volgens het reisprogramma",
 "Een fles mineraalwater per persoon per dag",
 "Airconditioned vervoer afgestemd op het aantal deelnemers",
 "2 nachten in Tangkoko &amp; 1 nacht in Tomohon (dubbel/twin bed)",
 "Ervaren chauffeur &amp; gids",
 "Ranger bij het natuurpark Tangkoko",
 "Toegangskaarten voor attracties &amp; parkeergeld",
 "Maaltijden volgens de reisroute",
 "Reisdiensten volgens het programma",
 "2 flessen mineraalwater per dag",
 "2 nachten in Tangkoko (dubbel/twin bed)",
 "Maaltijden volgens het programma",
 "Privéboot naar 3 eilanden",
 "Ervaren reisgids &amp; bootsman",
 "Reisdiensten volgens de reisroute",
 "Airconditioned vervoer afgestemd op het aantal deelnemers",
 "Ervaren gids en chauffeur",
 "Parkeer- &amp; donatiegeld&nbsp;",
 "Een fles mineraalwater per persoon&nbsp;",
 "Reisdiensten volgens het programma",
 "Luchthaventransfer",
 "Greenfee op dag 2",
 "Golfkarretje en caddiekosten (fooi voor caddie niet inbegrepen) op dag 2",
 "Privéboot naar Lihaga-eiland",
 "Professionele reisgids op dag 3",
 "Privéboot naar Bunaken-eiland",
 "Greenfee op dag 2 &amp; 3",
 "Golfkarretje en caddiekosten (fooi voor caddie niet inbegrepen)&nbsp;",
 "Luchthaventransfer&nbsp;",
 "Kamer (tweepersoonsbezetting – dubbel/twin bed)",
 "Volpension maaltijden",
 "Volpensionpakket (gebaseerd op 2 ochtendduiken per dag gedurende 3 duikdagen)",
 '<p style="text-align:justify;">Volpensionpakket (gebaseerd op 2 ochtendduiken per dag gedurende 3 duikdagen)</p><p><i><strong>Tangkoko-tour</strong></i>:&nbsp;</p>',
 "Vervoer naar Tangkoko &amp; de Tunan-waterval",
 "1x lunch in een lokaal restaurant",
 "Ervaren gids &amp; chauffeur",
 "Alle toegangskaarten&nbsp;",
 "Een fles mineraalwater per persoon.",
 "Volpensionpakket (gebaseerd op 2 ochtendduiken per dag gedurende 2 duikdagen)",
 "Vervoer over land",
 "Privéboot naar Lihaga-eiland",
 "Ervaren reisgids",
 "Chauffeur &amp; bootsman",
 "Toegangskaarten voor toeristische attracties &amp; parkeergeld",
 "Lunch &amp; 1 fles mineraalwater per persoon",
 "Privéboot naar Gangga- &amp; Lihaga-eiland",
 "Snorkeluitrusting",
 "Ervaren reisgids, chauffeur &amp; bootsman",
 "Privaat vervoer over land (auto)&nbsp;",
 "Boot naar Manado Tua-eiland - Bunaken-eiland",
 "Ervaren reisgids&nbsp;",
 "Chauffeur &amp; bootsman&nbsp;",
 "Parkeergeld, lunchbox&nbsp;",
 "1 fles mineraalwater per persoon&nbsp;",
 "Vervoer&nbsp;",
 "Boot &amp; snorkeluitrusting",
]

EXC = [
 "Retourvliegticket", "Fooien voor gids &amp; chauffeur", "Optionele excursies",
 "Persoonlijke uitgaven buiten het pakket (extra maaltijden/drankjes, enz.)",
 "Kruierservice, luchthavenbelasting &amp; overgewicht bagage",
 "Persoonlijke uitgaven (wasserij, minibar, kamerservice, enz.)",
 "Reisverzekering", "Overige kosten niet vermeld in het reisprogramma", "Vliegticket",
 "Auto (ophalen &amp; terugbrengen) optioneel", "Luchthavenbelasting", "Kruier&nbsp;", "Hotel", "Gids",
 "Fooi voor chauffeur", "Overige kosten buiten het reisprogramma", "Kruier", "Maaltijden", "Fooien voor gids &amp; chauffeur",
 "Hotel,&nbsp;", "Fooien voor gids en chauffeur", "Alle overige kosten buiten het reisprogramma",
 "Alle overige kosten buiten het reisprogramma.", "Fooien voor gids en chauffeur", "Vervoer over land (auto)",
 "Retourvliegticket", "Extra kosten buiten het pakket (extra maaltijden/drankjes, enz.)",
 "Kruier, luchthavenbelasting &amp; overgewicht bagage", "Persoonlijke uitgaven (wasserij, minibar, kamerservice, enz.)",
 "Reisverzekering", "Overige kosten buiten het reisprogramma", "Retourvliegticket", "Fooien voor chauffeur &amp; gids",
 "Optionele excursies", "Kosten buiten het pakket (extra maaltijden/drankjes, enz.)", "Kruier, luchthavenbelasting &amp; overgewicht bagage",
 "En overige kosten buiten het reisprogramma", "&nbsp;Optionele excursie", "Vervoer over land (auto)&nbsp;",
 "Retourvliegtickets", "Verhuur van uitrusting", "Nitrox-vullingen",
 "Nachtduiken &amp; mandarijnvis-duiken", "Optionele excursies &amp; activiteiten", "Persoonlijke uitgaven",
 "Luchthavenbelasting &amp; overgewicht bagage", "Alle diensten die hierboven niet zijn vermeld",
 "Verhuur van duikuitrusting", "Vliegticket&nbsp;", "Kruierservice", "Hotelverblijf&nbsp;",
 "Fooien voor gids &amp; chauffeur", "Optionele excursies &amp; overige persoonlijke uitgaven niet vermeld in het programma",
]

bangun('nl', INC, EXC)
