# -*- coding: utf-8 -*-
"""Traduzione italiana delle voci uniche inclusions/exclusions."""
import sys
sys.path.insert(0, '.')
from _bullets_ko import bangun

INC = [
 "Trasporto con aria condizionata in base alla dimensione del gruppo",
 "Barca privata per l'<strong>isola di Bunaken&nbsp;</strong>",
 "3 notti di soggiorno nell'hotel selezionato – camera twin/doppia",
 "Guida esperta &amp; conducente",
 "Biglietti d'ingresso alle attrazioni turistiche &amp; parcheggio",
 "Pasti secondo il programma",
 "Servizi turistici secondo l'itinerario",
 "Acqua minerale 1 bottiglia/persona/giorno",
 "Servizio di accoglienza",
 "Barca privata per <strong>l'isola di Bunaken &amp; l'isola di Lihaga</strong>",
 "4 notti di soggiorno nell'hotel selezionato – camera twin/doppia",
 "Barca privata per l'isola di Lihaga",
 "2 notti di soggiorno nell'hotel selezionato – camera twin/doppia",
 "Barca privata per <strong>l'isola di Bunaken</strong>",
 "Istruttore professionista di parapendio",
 "Biglietti d'ingresso alle attrazioni",
 "Servizi turistici secondo il programma",
 "Trasporto con aria condizionata in base al numero di partecipanti",
 "Guida esperta di mangrovie e conducente",
 "Canoa",
 "Biglietti d'ingresso alle attrazioni turistiche&nbsp;",
 "Parcheggio",
 "1 bottiglia d'acqua minerale a persona",
 "Trasporto interamente con aria condizionata in base al numero di partecipanti",
 "Ranger presso la riserva naturale di Tangkoko",
 "Guida e conducente esperti",
 "Biglietti d'ingresso alle attrazioni turistiche",
 "Pranzo",
 "Una bottiglia d'acqua minerale a persona",
 "Guida e conducente esperti, biglietti d'ingresso alle attrazioni turistiche",
 "Servizi secondo il programma",
 "Attrezzatura da rafting",
 "Barca privata per l'isola di Bunaken",
 "Guida turistica esperta &amp; timoniere",
 "Biglietti d'ingresso alle attrazioni turistiche",
 "Pranzo in un ristorante locale",
 "Una bottiglia d'acqua minerale a persona",
 "Servizi turistici secondo l'itinerario",
 "Trasporto con aria condizionata in base al numero di partecipanti",
 "Guida esperta (parlante inglese) &amp; conducente",
 "Biglietti d'ingresso &amp; parcheggio",
 "Servizi turistici secondo il programma",
 "Trasporto con aria condizionata&nbsp;",
 "Barca privata per l'isola di Bunaken",
 "Soggiorno di 5 notti in hotel, occupazione doppia",
 "Biglietti d'ingresso alle attrazioni turistiche &amp; parcheggio",
 "Pasti secondo il programma del tour",
 "Una bottiglia d'acqua minerale a persona al giorno",
 "Trasporto con aria condizionata in base al numero di partecipanti",
 "2 notti a Tangkoko &amp; 1 notte a Tomohon (letto doppio/twin)",
 "Conducente &amp; guida esperti",
 "Ranger presso il parco naturale di Tangkoko",
 "Biglietti d'ingresso alle attrazioni &amp; parcheggio",
 "Pasti secondo l'itinerario del tour",
 "Servizi turistici secondo il programma",
 "2 bottiglie d'acqua minerale al giorno",
 "2 notti a Tangkoko (letto doppio/twin)",
 "Pasti secondo il programma",
 "Barca privata per 3 isole",
 "Guida turistica esperta &amp; timoniere",
 "Servizi turistici secondo l'itinerario",
 "Trasporto con aria condizionata in base al numero di partecipanti",
 "Guida e conducente esperti",
 "Parcheggio &amp; contributo&nbsp;",
 "Una bottiglia d'acqua minerale a persona&nbsp;",
 "Servizi turistici secondo il programma",
 "Trasferimento aeroportuale",
 "Green fee al 2° giorno",
 "Golf cart e tariffa caddy (mancia caddy esclusa) al 2° giorno",
 "Barca privata per l'isola di Lihaga",
 "Guida turistica professionale al 3° giorno",
 "Barca privata per l'isola di Bunaken",
 "Green fee al 2° &amp; 3° giorno",
 "Golf cart e tariffa caddy (mancia caddy esclusa)&nbsp;",
 "Trasferimento aeroportuale&nbsp;",
 "Camera (occupazione doppia – letti doppi/twin)",
 "Pasti in pensione completa",
 "Pacchetto pensione completa (basato su 2 immersioni al mattino al giorno per 3 giorni di immersione)",
 '<p style="text-align:justify;">Pacchetto pensione completa (basato su 2 immersioni al mattino al giorno per 3 giorni di immersione)</p><p><i><strong>Tour di Tangkoko</strong></i>:&nbsp;</p>',
 "Trasporto verso Tangkoko &amp; la cascata di Tunan",
 "1x pranzo in un ristorante locale",
 "Guida esperta &amp; conducente",
 "Tutti i biglietti d'ingresso&nbsp;",
 "Una bottiglia d'acqua minerale a persona.",
 "Pacchetto pensione completa (basato su 2 immersioni al mattino al giorno per 2 giorni di immersione)",
 "Trasporto terrestre",
 "Barca privata per l'isola di Lihaga",
 "Guida turistica esperta",
 "Conducente &amp; timoniere",
 "Biglietti d'ingresso alle attrazioni turistiche &amp; parcheggio",
 "Pranzo &amp; 1 bottiglia d'acqua minerale a persona",
 "Barca privata per le isole di Gangga &amp; Lihaga",
 "Attrezzatura per snorkeling",
 "Guida turistica, conducente &amp; timoniere esperti",
 "Trasporto terrestre privato (auto)&nbsp;",
 "Barca per l'isola di Manado Tua - isola di Bunaken",
 "Guida turistica esperta&nbsp;",
 "Conducente &amp; timoniere&nbsp;",
 "Parcheggio, cestino da pranzo&nbsp;",
 "1 bottiglia d'acqua minerale a persona&nbsp;",
 "Trasporto&nbsp;",
 "Barca &amp; attrezzatura per snorkeling",
]

EXC = [
 "Biglietto aereo di andata e ritorno", "Mance per guida &amp; conducente", "Escursioni facoltative",
 "Spese personali fuori dal pacchetto (pasti/bevande extra, ecc.)",
 "Servizio portabagagli, tassa aeroportuale &amp; supplemento bagaglio in eccesso",
 "Spese personali (lavanderia, minibar, servizio in camera, ecc.)",
 "Assicurazione di viaggio", "Altre spese non menzionate nel programma del tour", "Biglietto aereo",
 "Auto (consegna &amp; ritiro) facoltativa", "Tassa aeroportuale", "Portabagagli&nbsp;", "Hotel", "Guida",
 "Mancia per il conducente", "Altre spese fuori dal programma del tour", "Portabagagli", "Pasti", "Mance per guida &amp; conducente",
 "Hotel,&nbsp;", "Mance per guida e conducente", "Qualsiasi altra spesa fuori dal programma del tour",
 "Qualsiasi altra spesa fuori dal programma del tour.", "Mance per guida e conducente", "Trasporto terrestre (auto)",
 "Biglietto aereo di andata e ritorno", "Spese aggiuntive fuori dal pacchetto (pasti/bevande extra, ecc.)",
 "Portabagagli, tassa aeroportuale &amp; bagaglio in eccesso", "Spese personali (lavanderia, minibar, servizio in camera, ecc.)",
 "Assicurazione di viaggio", "Altre spese fuori dal programma del tour", "Biglietto aereo di andata e ritorno", "Mance per conducente &amp; guida",
 "Escursioni facoltative", "Spese fuori dal pacchetto (pasti/bevande extra, ecc.)", "Portabagagli, tassa aeroportuale &amp; bagaglio in eccesso",
 "E altre spese fuori dal programma del tour", "&nbsp;Escursione facoltativa", "Trasporto terrestre (auto)&nbsp;",
 "Biglietti aerei di andata e ritorno", "Noleggio attrezzatura", "Ricariche nitrox",
 "Immersioni notturne &amp; del pesce mandarino", "Escursioni &amp; attività facoltative", "Spese personali",
 "Tassa aeroportuale &amp; bagaglio in eccesso", "Qualsiasi servizio non menzionato sopra",
 "Noleggio attrezzatura da immersione", "Biglietto aereo&nbsp;", "Servizio portabagagli", "Alloggio in hotel&nbsp;",
 "Mance per guida &amp; conducente", "Escursioni facoltative &amp; altre spese personali non menzionate nel programma",
]

bangun('it', INC, EXC)
