# -*- coding: utf-8 -*-
"""Deutsche Übersetzung der eindeutigen Inclusions-/Exclusions-Einträge."""
import sys
sys.path.insert(0, '.')
from _bullets_ko import bangun

INC = [
 "Klimatisierter Transport entsprechend der Gruppengröße",
 "Privatboot zur <strong>Insel Bunaken&nbsp;</strong>",
 "3 Nächte Unterkunft im ausgewählten Hotel – Doppel-/Twin-Zimmer",
 "Erfahrener Reiseleiter &amp; Fahrer",
 "Eintrittsgebühren zu Sehenswürdigkeiten &amp; Parkgebühren",
 "Mahlzeiten gemäß Programm",
 "Reiseleistungen gemäß Reiseverlauf",
 "Mineralwasser 1 Flasche/Person/Tag",
 "Empfangsservice",
 "Privatboot zur <strong>Insel Bunaken &amp; Insel Lihaga</strong>",
 "4 Nächte Unterkunft im ausgewählten Hotel – Doppel-/Twin-Zimmer",
 "Privatboot zur Insel Lihaga",
 "2 Nächte Unterkunft im ausgewählten Hotel – Doppel-/Twin-Zimmer",
 "Privatboot zur <strong>Insel Bunaken</strong>",
 "Professioneller Gleitschirm-Fluglehrer",
 "Eintrittsgebühren zu Sehenswürdigkeiten",
 "Reiseleistungen gemäß Programm",
 "Vollständig klimatisierter Transport entsprechend der Teilnehmerzahl",
 "Erfahrener Mangroven-Guide und Fahrer",
 "Kanu",
 "Eintrittsgebühren zu Sehenswürdigkeiten&nbsp;",
 "Parkgebühren",
 "1 Flasche Mineralwasser pro Person",
 "Vollständig klimatisierter Transport entsprechend der Teilnehmerzahl",
 "Ranger im Naturschutzgebiet Tangkoko",
 "Erfahrener Reiseleiter und Fahrer",
 "Eintrittsgebühren zu Sehenswürdigkeiten",
 "Mittagessen",
 "Eine Flasche Mineralwasser pro Person",
 "Erfahrener Reiseleiter und Fahrer, Eintrittsgebühren zu Sehenswürdigkeiten",
 "Leistungen gemäß Programm",
 "Rafting-Ausrüstung",
 "Privatboot zur Insel Bunaken",
 "Erfahrener Reiseleiter &amp; Bootsführer",
 "Eintrittsgebühren zu Sehenswürdigkeiten",
 "Mittagessen in einem lokalen Restaurant",
 "Eine Flasche Mineralwasser pro Person",
 "Reiseleistungen gemäß Reiseverlauf",
 "Klimatisierter Transport entsprechend der Teilnehmerzahl",
 "Erfahrener Reiseleiter (englischsprachig) &amp; Fahrer",
 "Eintritts- &amp; Parkgebühren",
 "Reiseleistungen gemäß Programm",
 "Klimatisierter Transport&nbsp;",
 "Privatboot zur Insel Bunaken",
 "5 Nächte Hotelaufenthalt, Doppelbelegung",
 "Eintrittskarten zu Sehenswürdigkeiten &amp; Parkgebühren",
 "Mahlzeiten gemäß Reiseprogramm",
 "Eine Flasche Mineralwasser pro Person und Tag",
 "Klimatisierter Transport entsprechend der Teilnehmerzahl",
 "2 Nächte in Tangkoko &amp; 1 Nacht in Tomohon (Doppel-/Twin-Bett)",
 "Erfahrener Fahrer &amp; Reiseleiter",
 "Ranger im Naturpark Tangkoko",
 "Eintrittskarten zu Sehenswürdigkeiten &amp; Parkgebühren",
 "Mahlzeiten gemäß Reiseverlauf",
 "Reiseleistungen gemäß Programm",
 "2 Flaschen Mineralwasser pro Tag",
 "2 Nächte in Tangkoko (Doppel-/Twin-Bett)",
 "Mahlzeiten gemäß Programm",
 "Privatboot zu 3 Inseln",
 "Erfahrener Reiseleiter &amp; Bootsführer",
 "Reiseleistungen gemäß Reiseverlauf",
 "Klimatisierter Transport entsprechend der Teilnehmerzahl",
 "Erfahrener Reiseleiter und Fahrer",
 "Park- &amp; Spendengebühren&nbsp;",
 "Eine Flasche Mineralwasser pro Person&nbsp;",
 "Reiseleistungen gemäß Programm",
 "Flughafentransfer",
 "Greenfee am 2. Tag",
 "Golfwagen und Caddiegebühr (Caddie-Trinkgeld ausgeschlossen) am 2. Tag",
 "Privatboot zur Insel Lihaga",
 "Professioneller Reiseleiter am 3. Tag",
 "Privatboot zur Insel Bunaken",
 "Greenfee am 2. &amp; 3. Tag",
 "Golfwagen und Caddiegebühr (Caddie-Trinkgeld ausgeschlossen)&nbsp;",
 "Flughafentransfer&nbsp;",
 "Zimmer (Doppelbelegung – Doppel-/Twin-Betten)",
 "Vollpension",
 "Vollpensionspaket (basierend auf 2 morgendlichen Tauchgängen pro Tag über 3 Tauchtage)",
 '<p style="text-align:justify;">Vollpensionspaket (basierend auf 2 morgendlichen Tauchgängen pro Tag über 3 Tauchtage)</p><p><i><strong>Tangkoko-Tour</strong></i>:&nbsp;</p>',
 "Transport nach Tangkoko &amp; zum Tunan-Wasserfall",
 "1x Mittagessen in einem lokalen Restaurant",
 "Erfahrener Reiseleiter &amp; Fahrer",
 "Alle Eintrittsgebühren&nbsp;",
 "Eine Flasche Mineralwasser pro Person.",
 "Vollpensionspaket (basierend auf 2 morgendlichen Tauchgängen pro Tag über 2 Tauchtage)",
 "Landtransport",
 "Privatboot zur Insel Lihaga",
 "Erfahrener Reiseleiter",
 "Fahrer &amp; Bootsführer",
 "Eintrittsgebühren zu Sehenswürdigkeiten &amp; Parkgebühren",
 "Mittagessen &amp; 1 Flasche Mineralwasser pro Person",
 "Privatboot zu den Inseln Gangga &amp; Lihaga",
 "Schnorchelausrüstung",
 "Erfahrener Reiseleiter, Fahrer &amp; Bootsführer",
 "Privater Landtransport (Pkw)&nbsp;",
 "Boot zur Insel Manado Tua - Insel Bunaken",
 "Erfahrener Reiseleiter&nbsp;",
 "Fahrer &amp; Bootsführer&nbsp;",
 "Parkgebühren, Lunchpaket&nbsp;",
 "1 Flasche Mineralwasser pro Person&nbsp;",
 "Transport&nbsp;",
 "Boot &amp; Schnorchelausrüstung",
]

EXC = [
 "Flugticket hin und zurück", "Trinkgelder für Reiseleiter &amp; Fahrer", "Optionale Ausflüge",
 "Persönliche Ausgaben außerhalb des Pakets (zusätzliche Mahlzeiten/Getränke usw.)",
 "Gepäckträgerservice, Flughafensteuer &amp; Übergepäckgebühren",
 "Persönliche Ausgaben (Wäscheservice, Minibar, Zimmerservice usw.)",
 "Reiseversicherung", "Sonstige im Reiseprogramm nicht erwähnte Kosten", "Flugticket",
 "Fahrzeug (Abholung &amp; Rückgabe) optional", "Flughafensteuer", "Gepäckträger&nbsp;", "Hotel", "Reiseleiter",
 "Trinkgeld für Fahrer", "Sonstige Kosten außerhalb des Reiseprogramms", "Gepäckträger", "Mahlzeiten", "Trinkgelder für Reiseleiter &amp; Fahrer",
 "Hotel,&nbsp;", "Trinkgelder für Reiseleiter und Fahrer", "Jegliche sonstige Kosten außerhalb des Reiseprogramms",
 "Jegliche sonstige Kosten außerhalb des Reiseprogramms.", "Trinkgelder für Reiseleiter und Fahrer", "Landtransport (Pkw)",
 "Flugticket hin und zurück", "Zusätzliche Kosten außerhalb des Pakets (zusätzliche Mahlzeiten/Getränke usw.)",
 "Gepäckträger, Flughafensteuer &amp; Übergepäck", "Persönliche Ausgaben (Wäscheservice, Minibar, Zimmerservice usw.)",
 "Reiseversicherung", "Sonstige Kosten außerhalb des Reiseprogramms", "Flugticket hin und zurück", "Trinkgelder für Fahrer &amp; Reiseleiter",
 "Optionale Ausflüge", "Kosten außerhalb des Pakets (zusätzliche Mahlzeiten/Getränke usw.)", "Gepäckträger, Flughafensteuer &amp; Übergepäck",
 "Und sonstige Kosten außerhalb des Reiseprogramms", "&nbsp;Optionaler Ausflug", "Landtransport (Pkw)&nbsp;",
 "Flugtickets hin und zurück", "Ausrüstungsverleih", "Nitrox-Füllungen",
 "Nacht- &amp; Mandarinfisch-Tauchgänge", "Optionale Ausflüge &amp; Aktivitäten", "Persönliche Ausgaben",
 "Flughafensteuer &amp; Übergepäck", "Sämtliche oben nicht erwähnten Leistungen",
 "Tauchausrüstungsverleih", "Flugticket&nbsp;", "Gepäckträgerservice", "Hotelunterkunft&nbsp;",
 "Trinkgelder für Reiseleiter &amp; Fahrer", "Optionale Ausflüge &amp; sonstige im Programm nicht erwähnte persönliche Ausgaben",
]

bangun('de', INC, EXC)
