# -*- coding: utf-8 -*-
"""Traducción española de los elementos únicos de inclusions/exclusions."""
import sys
sys.path.insert(0, '.')
from _bullets_ko import bangun

INC = [
 "Transporte con aire acondicionado según el tamaño del grupo",
 "Barco privado a la <strong>isla de Bunaken&nbsp;</strong>",
 "3 noches de alojamiento en el hotel seleccionado – habitación twin/doble",
 "Guía experto &amp; conductor",
 "Entradas a las atracciones turísticas &amp; estacionamiento",
 "Comidas según el programa",
 "Servicios turísticos según el itinerario",
 "Agua mineral 1 botella/persona/día",
 "Servicio de recepción",
 "Barco privado a <strong>la isla de Bunaken &amp; la isla de Lihaga</strong>",
 "4 noches de alojamiento en el hotel seleccionado – habitación twin/doble",
 "Barco privado a la isla de Lihaga",
 "2 noches de alojamiento en el hotel seleccionado – habitación twin/doble",
 "Barco privado a la <strong>isla de Bunaken</strong>",
 "Instructor profesional de parapente",
 "Entradas a las atracciones",
 "Servicios turísticos según el programa",
 "Transporte con aire acondicionado según el número de participantes",
 "Guía experto de manglares y conductor",
 "Canoa",
 "Entradas a las atracciones turísticas&nbsp;",
 "Estacionamiento",
 "1 botella de agua mineral por persona",
 "Transporte totalmente con aire acondicionado según el número de participantes",
 "Guardaparques en la reserva natural de Tangkoko",
 "Guía y conductor expertos",
 "Entradas a las atracciones turísticas",
 "Almuerzo",
 "Una botella de agua mineral por persona",
 "Guía y conductor expertos, entradas a las atracciones turísticas",
 "Servicios según el programa",
 "Equipo de rafting",
 "Barco privado a la isla de Bunaken",
 "Guía turístico experto &amp; timonel",
 "Entradas a las atracciones turísticas",
 "Almuerzo en un restaurante local",
 "Una botella de agua mineral por persona",
 "Servicios turísticos según el itinerario",
 "Transporte con aire acondicionado según el número de participantes",
 "Guía experto (de habla inglesa) &amp; conductor",
 "Entradas &amp; estacionamiento",
 "Servicios turísticos según el programa",
 "Transporte con aire acondicionado&nbsp;",
 "Barco privado a la isla de Bunaken",
 "Estancia de 5 noches en hotel, ocupación doble",
 "Entradas a las atracciones turísticas &amp; estacionamiento",
 "Comidas según el programa del tour",
 "Una botella de agua mineral por persona al día",
 "Transporte con aire acondicionado según el número de participantes",
 "2 noches en Tangkoko &amp; 1 noche en Tomohon (cama doble/twin)",
 "Conductor &amp; guía expertos",
 "Guardaparques en el parque natural de Tangkoko",
 "Entradas a las atracciones &amp; estacionamiento",
 "Comidas según el itinerario del tour",
 "Servicios turísticos según el programa",
 "2 botellas de agua mineral al día",
 "2 noches en Tangkoko (cama doble/twin)",
 "Comidas según el programa",
 "Barco privado a 3 islas",
 "Guía turístico experto &amp; timonel",
 "Servicios turísticos según el itinerario",
 "Transporte con aire acondicionado según el número de participantes",
 "Guía y conductor expertos",
 "Estacionamiento &amp; donativo&nbsp;",
 "Una botella de agua mineral por persona&nbsp;",
 "Servicios turísticos según el programa",
 "Traslado al aeropuerto",
 "Green fee el día 2",
 "Carrito de golf y tarifa de caddie (propina del caddie excluida) el día 2",
 "Barco privado a la isla de Lihaga",
 "Guía turístico profesional el día 3",
 "Barco privado a la isla de Bunaken",
 "Green fee los días 2 &amp; 3",
 "Carrito de golf y tarifa de caddie (propina del caddie excluida)&nbsp;",
 "Traslado al aeropuerto&nbsp;",
 "Habitación (ocupación doble – camas doble/twin)",
 "Comidas en pensión completa",
 "Paquete de pensión completa (basado en 2 inmersiones matutinas por día durante 3 días de inmersión)",
 '<p style="text-align:justify;">Paquete de pensión completa (basado en 2 inmersiones matutinas por día durante 3 días de inmersión)</p><p><i><strong>Tour a Tangkoko</strong></i>:&nbsp;</p>',
 "Transporte a Tangkoko &amp; la cascada de Tunan",
 "1x almuerzo en un restaurante local",
 "Guía experto &amp; conductor",
 "Todas las entradas&nbsp;",
 "Una botella de agua mineral por persona.",
 "Paquete de pensión completa (basado en 2 inmersiones matutinas por día durante 2 días de inmersión)",
 "Transporte terrestre",
 "Barco privado a la isla de Lihaga",
 "Guía turístico experto",
 "Conductor &amp; timonel",
 "Entradas a las atracciones turísticas &amp; estacionamiento",
 "Almuerzo &amp; 1 botella de agua mineral por persona",
 "Barco privado a las islas de Gangga &amp; Lihaga",
 "Equipo de snorkel",
 "Guía turístico, conductor &amp; timonel expertos",
 "Transporte terrestre privado (automóvil)&nbsp;",
 "Barco a la isla de Manado Tua - isla de Bunaken",
 "Guía turístico experto&nbsp;",
 "Conductor &amp; timonel&nbsp;",
 "Estacionamiento, caja de almuerzo&nbsp;",
 "1 botella de agua mineral por persona&nbsp;",
 "Transporte&nbsp;",
 "Barco &amp; equipo de snorkel",
]

EXC = [
 "Boleto de avión de ida y vuelta", "Propinas para el guía &amp; el conductor", "Excursiones opcionales",
 "Gastos personales fuera del paquete (comidas/bebidas adicionales, etc.)",
 "Servicio de mozos, impuesto aeroportuario &amp; exceso de equipaje",
 "Gastos personales (lavandería, minibar, servicio a la habitación, etc.)",
 "Seguro de viaje", "Otros gastos no mencionados en el programa del tour", "Boleto de avión",
 "Automóvil (recogida &amp; devolución) opcional", "Impuesto aeroportuario", "Mozos&nbsp;", "Hotel", "Guía",
 "Propina del conductor", "Otros gastos fuera del programa del tour", "Mozos", "Comidas", "Propinas para el guía &amp; el conductor",
 "Hotel,&nbsp;", "Propinas para el guía y el conductor", "Cualquier otro gasto fuera del programa del tour",
 "Cualquier otro gasto fuera del programa del tour.", "Propinas para el guía y el conductor", "Transporte terrestre (automóvil)",
 "Boleto de avión de ida y vuelta", "Gastos adicionales fuera del paquete (comidas/bebidas adicionales, etc.)",
 "Mozos, impuesto aeroportuario &amp; exceso de equipaje", "Gastos personales (lavandería, minibar, servicio a la habitación, etc.)",
 "Seguro de viaje", "Otros gastos fuera del programa del tour", "Boleto de avión de ida y vuelta", "Propinas para el conductor &amp; el guía",
 "Excursiones opcionales", "Gastos fuera del paquete (comidas/bebidas adicionales, etc.)", "Mozos, impuesto aeroportuario &amp; exceso de equipaje",
 "Y otros gastos fuera del programa del tour", "&nbsp;Excursión opcional", "Transporte terrestre (automóvil)&nbsp;",
 "Boletos de avión de ida y vuelta", "Alquiler de equipo", "Recargas de nitrox",
 "Inmersiones nocturnas &amp; del pez mandarín", "Excursiones &amp; actividades opcionales", "Gastos personales",
 "Impuesto aeroportuario &amp; exceso de equipaje", "Cualquier servicio no mencionado anteriormente",
 "Alquiler de equipo de buceo", "Boleto de avión&nbsp;", "Servicio de mozos", "Alojamiento en hotel&nbsp;",
 "Propinas para el guía &amp; el conductor", "Excursiones opcionales &amp; otros gastos personales no mencionados en el programa",
]

bangun('es', INC, EXC)
